FROM php:8.1-cli

RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    libzip-dev libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

CMD ["composer", "create-project", "--prefer-dist", "laravel/laravel", "."]
